different getStateFromStore functions
Strencher/BetterDiscordStuff pull request #383
Opened 2023-12-19 21:37 UTC by Lemming8

2023-12-22 09:45 UTC, domi-btnr requested changes

2023-12-22 09:45 UTC, domi-btnr commented on ShowAllActivities/components/wrapper.jsx
> +import { Utils } from "@api";
Please don't change the formatting

2023-12-22 17:46 UTC, Lemming8 commented on ShowAllActivities/components/wrapper.jsx
> +import { Utils } from "@api";
Sorry, didn't see that one

2024-01-09 09:53 UTC, domi-btnr approved these changes

2024-01-09 10:06 UTC, merged